export const siteConfig = {
  name: "Dory - AI Native Data Workspace, Database Client, SQL Console With AI Assistance",
  description:
    "Navicat alternative - Dory is an AI native database client and SQL console that helps developers and data professionals manage databases more efficiently with AI assistance.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://getdory.dev",
  locale: "en_US",
  creator: "Dory Team",
  keywords: [
    "free database client",
    "Free SQL Client",
    "open source database client",
    "open source",
    "SQL Client",
    "database management",
    "AI assistance",
    "data workspace",
    "SQL console",
    "database client",
    "AI native",
    "developer tools",
    "SQL editor",
    "data professional",
    "Navicat alternative",
    "data management",
    "database tools",
    "AI-powered SQL",
    "data analysis",
    "database administration",
    "SQL query builder",
    "data visualization",
    "cloud database",
    "database connectivity",
    "data integration",
    "database automation",
    "data collaboration",
    "SQL performance optimization",
    "data security",
    "database monitoring",
    "AI-driven insights",
    "data engineering",
    "database development",
    "SQL scripting",
    "data migration",
    "database backup",
    "data warehousing",
    "DBeaver alternative",
    "HeidiSQL alternative",
    "DataGrip alternative",
    "Chat2DB alternative",
  ],
  social: {
    twitter: "@dorystudio",
  },
  getStartedUrl:
    "https://getdory.dev/getting-started/introduction",
  ogImage: "https://getdory.dev/og.png",
  links: {
    twitter: "https://x.com/dorystudio",
    github: "https://github.com/dorylab/dory",
    email: "mailto:contact@dorystudio.com",
  },
  stats: {
    figma: 7693,
    github: 1829,
    cli: 16493,
    total: "26.1k+",
    updated: "13 Jan 2026",
    sections: 74,
    illustrations: 23,
    animations: 15,
    templates: 7,
  },
}

export type SiteConfig = typeof siteConfig
